import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { ArrowRight, Plus, Search } from 'lucide-react'
import { tasksApi } from '../services/tasks-api'
import type { Task, TaskGroup, TaskPriority } from '../types'

interface Props { onOpen: (id: string) => void }
const groups: { id: TaskGroup; label: string; tone: string }[] = [{ id: 'overdue', label: 'Vencidas', tone: 'text-[#8e1f33]' }, { id: 'today', label: 'Hoy', tone: 'text-plum' }, { id: 'upcoming', label: 'Próximas', tone: 'text-copy' }, { id: 'unscheduled', label: 'Sin fecha', tone: 'text-copy' }]
const priority: Record<TaskPriority, string> = { Alta: 'bg-[#fae3d3] text-[#8a4715]', Media: 'bg-[#f5eed0] text-[#6b5a10]', Baja: 'bg-[#e9e4ee] text-copy', 'Sin prioridad': 'bg-[#e9e4ee] text-copy' }

export function TasksPage({ onOpen }: Props) {
  const [tasks, setTasks] = useState<Task[]>([]); const [scope, setScope] = useState<'mine' | 'team' | 'unassigned'>('mine'); const [search, setSearch] = useState(''); const [creating, setCreating] = useState(false)
  const load = () => tasksApi.getAll().then(setTasks)
  useEffect(() => { load() }, [])
  const visible = useMemo(() => tasks.filter((task) => (scope === 'mine' ? task.responsible === 'María Solana' : scope === 'unassigned' ? task.responsible === 'Sin asignar' : true) && `${task.title} ${task.depositCode ?? ''} ${task.contentCode ?? ''} ${task.lotCode ?? ''} ${task.detail}`.toLocaleLowerCase('es').includes(search.trim().toLocaleLowerCase('es'))), [scope, search, tasks])
  return <div className="mx-auto max-w-6xl space-y-4 pb-6"><header className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[11px] text-muted">Tareas · Centro Norte</p><h1 className="mt-1 text-[23px] font-semibold">Tareas</h1><p className="mt-1 text-xs text-muted">{tasks.length} pendientes · agenda agrupada por vencimiento.</p></div><button onClick={() => setCreating(true)} className="min-h-10 rounded-xl bg-plum px-4 text-xs font-semibold text-white"><Plus className="mr-1 inline size-4" />Crear tarea</button></header><div className="flex flex-wrap gap-2"><div className="flex rounded-xl border border-border bg-white p-1">{([{ id: 'mine', label: 'Mis tareas' }, { id: 'team', label: 'Equipo' }, { id: 'unassigned', label: 'Sin asignar' }] as const).map((item) => <button key={item.id} onClick={() => setScope(item.id)} className={`rounded-lg px-3 py-2 text-xs font-semibold ${scope === item.id ? 'bg-plum-soft text-plum' : 'text-copy'}`}>{item.label}</button>)}</div><label className="flex h-10 min-w-[220px] flex-1 items-center gap-2 rounded-xl border border-border bg-white px-3 text-xs text-muted sm:max-w-sm"><Search className="size-4" /><input value={search} onChange={(event) => setSearch(event.target.value)} className="min-w-0 flex-1 bg-transparent outline-none" placeholder="Filtrar por zona o tipo" /></label></div><div className="space-y-5">{groups.map((group) => { const items = visible.filter((task) => task.group === group.id); if (!items.length) return null; return <section key={group.id}><h2 className={`mb-2 text-[11px] font-semibold uppercase tracking-[0.08em] ${group.tone}`}>{group.label} <span className="font-mono">{items.length}</span></h2><div className="space-y-2">{items.map((task) => <TaskRow key={task.id} task={task} onOpen={onOpen} />)}</div></section> })}{!visible.length && <p className="rounded-2xl border border-border bg-white p-8 text-center text-xs text-muted">No hay tareas que coincidan con este filtro.</p>}</div>{creating && <CreateTask onClose={() => setCreating(false)} onSaved={async (input) => { const task = await tasksApi.create(input); setCreating(false); load(); onOpen(task.id) }} />}</div>
}
function TaskRow({ task, onOpen }: { task: Task; onOpen: (id: string) => void }) { return <button onClick={() => onOpen(task.id)} className={`grid w-full gap-2 rounded-2xl border bg-white p-4 text-left hover:bg-plum-soft sm:grid-cols-[auto_minmax(0,1fr)_auto_auto_auto] sm:items-center sm:gap-4 ${task.group === 'overdue' ? 'border-[#f0d9de]' : 'border-border'}`}><span className={`w-fit rounded-full px-2 py-1 text-[10px] font-semibold ${priority[task.priority]}`}>{task.priority}</span><span className="min-w-0"><span className="block text-xs font-semibold">{task.title}{task.partial && <span className="ml-2 rounded-full bg-[#dceadf] px-1.5 py-0.5 text-[9px] text-[#1f5c3a]">Parcialmente realizada</span>}</span><span className="mt-1 block text-[11px] text-muted">{[task.depositCode, task.contentCode, task.lotCode, task.detail].filter(Boolean).join(' · ')}</span></span><span className={`font-mono text-xs ${task.group === 'overdue' ? 'text-[#8e1f33]' : 'text-copy'}`}>{task.dueLabel}</span><span className="text-xs text-copy">{task.responsible}</span><ArrowRight className="size-4 text-plum" /></button> }
function CreateTask({ onClose, onSaved }: { onClose: () => void; onSaved: (input: Pick<Task, 'title' | 'priority' | 'dueLabel' | 'depositCode' | 'contentCode' | 'detail'>) => Promise<void> }) { const [form, setForm] = useState({ title: '', priority: 'Media' as TaskPriority, dueLabel: 'hoy 17:00', depositCode: '', contentCode: '', detail: '' }); const [saving, setSaving] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.title.trim()) return; setSaving(true); await onSaved(form); setSaving(false) }; return <div className="fixed inset-0 z-30 flex items-end justify-center bg-[#2e262a]/30 p-4 sm:items-center" onMouseDown={onClose}><form onSubmit={submit} onMouseDown={(event) => event.stopPropagation()} className="w-full max-w-lg rounded-2xl bg-[#fdfbfc] p-5 shadow-xl"><h2 className="text-lg font-semibold">Crear tarea</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Título" value={form.title} onChange={(title) => setForm({ ...form, title })} /><label className="text-xs font-semibold">Prioridad<select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value as TaskPriority })} className="mt-1 w-full rounded-xl border border-border bg-white p-3 text-sm font-normal"><option>Alta</option><option>Media</option><option>Baja</option><option>Sin prioridad</option></select></label><Field label="Depósito" value={form.depositCode} onChange={(depositCode) => setForm({ ...form, depositCode })} /><Field label="Contenido" value={form.contentCode} onChange={(contentCode) => setForm({ ...form, contentCode })} /></div><label className="mt-3 block text-xs font-semibold">Detalle<textarea value={form.detail} onChange={(event) => setForm({ ...form, detail: event.target.value })} className="mt-1 min-h-20 w-full rounded-xl border border-border bg-white p-3 text-sm font-normal" /></label><div className="mt-4 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-xl border border-border px-4 py-3 text-xs font-semibold">Cancelar</button><button disabled={saving || !form.title.trim()} className="rounded-xl bg-plum px-4 py-3 text-xs font-semibold text-white disabled:opacity-60">{saving ? 'Creando…' : 'Crear y abrir'}</button></div></form></div> }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-xs font-semibold">{label}<input value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-xl border border-border bg-white p-3 text-sm font-normal" /></label> }
