import { useEffect, useState, type FormEvent } from 'react'
import { ArrowLeft, ArrowUpRight, Pencil, X } from 'lucide-react'
import { cellarApi } from '../services/cellar-api'
import type { Deposit, NewDeposit } from '../types'
import { activeOccupation, formatLiters, statusClass, statusLabel } from '../utils'

interface DepositDetailPageProps {
  code: string
  onBack: () => void
  onOpenLots: () => void
  onOpenContent: (code: string) => void
  onRegisterMovement: (code: string) => void
}

type Tab = 'Características' | 'Ocupaciones' | 'Limpieza y mantenimiento'
const tabs: Tab[] = ['Características', 'Ocupaciones', 'Limpieza y mantenimiento']

function EditDeposit({ deposit, onClose, onSaved }: { deposit: Deposit; onClose: () => void; onSaved: (deposit: Deposit) => void }) {
  const [form, setForm] = useState<Pick<NewDeposit, 'zone' | 'position' | 'capacityLiters' | 'material' | 'refrigerated'>>({ zone: deposit.zone, position: deposit.position, capacityLiters: deposit.capacityLiters, material: deposit.material, refrigerated: deposit.refrigerated })
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(''); try { onSaved(await cellarApi.updateDeposit(deposit.code, form)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'No se ha podido guardar.') } finally { setSaving(false) } }
  return <div className="fixed inset-0 z-30 flex justify-end bg-[#2e262a]/30" onMouseDown={onClose}><section role="dialog" aria-modal="true" aria-labelledby="edit-deposit-title" onMouseDown={(event) => event.stopPropagation()} className="h-full w-full max-w-[420px] overflow-y-auto bg-[#fdfbfc] p-5 shadow-xl sm:p-6"><div className="flex items-center justify-between"><h2 id="edit-deposit-title" className="text-[20px] font-semibold">Editar {deposit.code}</h2><button type="button" onClick={onClose} aria-label="Cerrar" className="rounded-lg p-2 hover:bg-plum-soft"><X className="size-4" /></button></div><p className="mt-2 text-[12px] text-muted">El volumen del contenido se cambia mediante un movimiento, no aquí.</p><form onSubmit={handleSubmit} className="mt-5 space-y-4"><p className="rounded-xl bg-plum-soft p-3 font-mono text-[12px] text-plum">{deposit.code} · {deposit.center}</p>{([['Zona', 'zone'], ['Posición', 'position']] as const).map(([label, key]) => <label key={key} className="block text-[12px] font-semibold text-copy">{label}<input required={key === 'zone'} value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="mt-1.5 h-10 w-full rounded-xl border border-border bg-white px-3 text-[13px] font-normal outline-none focus:border-[#b9899c]" /></label>)}<label className="block text-[12px] font-semibold text-copy">Capacidad útil (L)<input required type="number" min="1" value={form.capacityLiters} onChange={(event) => setForm({ ...form, capacityLiters: Number(event.target.value) })} className="mt-1.5 h-10 w-full rounded-xl border border-border bg-white px-3 text-[13px] font-normal outline-none focus:border-[#b9899c]" /></label><label className="block text-[12px] font-semibold text-copy">Material<select value={form.material} onChange={(event) => setForm({ ...form, material: event.target.value })} className="mt-1.5 h-10 w-full rounded-xl border border-border bg-white px-3 text-[13px] font-normal"><option>Inox</option><option>Hormigón</option><option>Madera</option></select></label><label className="flex items-center gap-2 text-[12px] text-copy"><input type="checkbox" checked={form.refrigerated} onChange={(event) => setForm({ ...form, refrigerated: event.target.checked })} />Refrigerado</label>{error && <p role="alert" className="text-[12px] text-[#8e3b4a]">{error}</p>}<button type="submit" disabled={saving} className="min-h-10 w-full rounded-xl bg-plum text-[12.5px] font-semibold text-white disabled:opacity-60">{saving ? 'Guardando…' : 'Guardar cambios'}</button></form></section></div>
}

export function DepositDetailPage({ code, onBack, onOpenLots, onOpenContent, onRegisterMovement }: DepositDetailPageProps) {
  const [deposit, setDeposit] = useState<Deposit>()
  const [loading, setLoading] = useState(true)
  const [tab, setTab] = useState<Tab>('Ocupaciones')
  const [editing, setEditing] = useState(false)
  const [notice, setNotice] = useState('')

  useEffect(() => { let mounted = true; setLoading(true); cellarApi.getDeposit(code).then((data) => { if (mounted) setDeposit(data) }).finally(() => { if (mounted) setLoading(false) }); return () => { mounted = false } }, [code])
  if (loading) return <p className="p-6 text-center text-[12px] text-muted">Cargando depósito…</p>
  if (!deposit) return <div className="rounded-2xl border border-border bg-white p-6"><p className="text-[13px]">No se encuentra el depósito {code}.</p><button type="button" onClick={onBack} className="text-[12px] font-semibold text-plum">Volver a depósitos</button></div>

  const occupation = activeOccupation(deposit)
  const occupiedLiters = occupation?.volumeLiters ?? 0
  const fill = Math.round(occupiedLiters / deposit.capacityLiters * 100)

  return <div className="space-y-4"><button type="button" onClick={onBack} className="flex items-center gap-1 text-[11.5px] font-semibold text-plum hover:underline"><ArrowLeft className="size-3.5" />Volver a depósitos</button><header className="rounded-[18px] border border-border bg-white p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h1 className="m-0 font-mono text-[22px] font-medium">{deposit.code}</h1><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${statusClass(deposit)}`}>{statusLabel(deposit)}</span></div><p className="mt-1 text-[12px] text-muted">{deposit.zone} · posición {deposit.position || 'sin indicar'} · útil {formatLiters(deposit.capacityLiters)} L</p><p className="mt-1 text-[11.5px] text-copy">Recipiente físico. El producto almacenado tiene su propia identidad e historial.</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setEditing(true)} className="flex min-h-9 items-center gap-1 rounded-xl border border-border px-3 text-[11.5px] font-semibold hover:bg-plum-soft"><Pencil className="size-3.5" />Editar</button>{deposit.status === 'available' ? <button type="button" onClick={onOpenLots} className="min-h-9 rounded-xl bg-plum px-3 text-[11.5px] font-semibold text-white">Registrar entrada</button> : occupation ? <><button type="button" onClick={() => setNotice(`Registrar muestra para ${occupation.contentCode}: vista de laboratorio pendiente.`)} className="min-h-9 rounded-xl bg-plum px-3 text-[11.5px] font-semibold text-white">Registrar muestra</button><button type="button" onClick={() => onRegisterMovement(deposit.code)} className="min-h-9 rounded-xl border border-border px-3 text-[11.5px] font-semibold">Registrar movimiento</button></> : null}</div></div></header>
    {occupation && <button type="button" onClick={() => onOpenContent(occupation.contentCode)} className="flex min-h-9 items-center gap-1 rounded-xl border border-border bg-white px-3 text-xs font-semibold text-plum">Abrir ficha del contenido {occupation.contentCode} <ArrowUpRight className="size-3.5" /></button>}
    {notice && <div role="status" className="flex items-start justify-between gap-3 rounded-xl border border-border bg-white p-3 text-[12px] text-copy"><span>{notice}</span><button type="button" onClick={() => setNotice('')} aria-label="Cerrar aviso"><X className="size-3.5" /></button></div>}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.45fr)_minmax(280px,1fr)]"><section className="min-w-0 rounded-[18px] border border-border bg-[#fdfbfc] p-4 sm:p-5"><div className="flex gap-1 overflow-x-auto border-b border-border" role="tablist" aria-label="Datos del depósito">{tabs.map((item) => <button key={item} type="button" role="tab" aria-selected={tab === item} onClick={() => setTab(item)} className={`shrink-0 border-b-2 px-3 py-2.5 text-[11.5px] font-semibold ${tab === item ? 'border-plum text-plum' : 'border-transparent text-muted'}`}>{item}</button>)}</div>
      {tab === 'Características' && <div className="mt-4 grid gap-3 sm:grid-cols-2">{[['Identificador', deposit.code], ['Centro', deposit.center], ['Zona y posición', `${deposit.zone} · ${deposit.position || 'sin indicar'}`], ['Capacidad útil', `${formatLiters(deposit.capacityLiters)} L`], ['Capacidad nominal', deposit.nominalCapacityLiters ? `${formatLiters(deposit.nominalCapacityLiters)} L` : 'No indicada'], ['Material y refrigeración', `${deposit.material} · ${deposit.refrigerated ? 'refrigerado' : 'sin refrigeración'}`]].map(([label, value]) => <div key={label} className="rounded-xl border border-border bg-white p-3"><div className="text-[11px] text-muted">{label}</div><div className="mt-1 text-[12.5px] font-semibold">{value}</div></div>)}<p className="sm:col-span-2 text-[11.5px] leading-5 text-muted">El volumen ocupado procede de los movimientos y no se edita entre estas características.</p></div>}
      {tab === 'Ocupaciones' && <div className="mt-4 space-y-2">{deposit.occupations.length === 0 ? <p className="rounded-xl bg-white p-5 text-[12px] text-muted">No hay ocupaciones registradas.</p> : deposit.occupations.map((item) => <div key={`${item.contentCode}-${item.entryDate}`} className="grid grid-cols-2 gap-2 rounded-xl border border-border bg-white p-3 text-[11.5px] sm:grid-cols-[1.2fr_1fr_1fr_1fr_1fr]"><div><span className="block text-[10px] text-muted sm:hidden">Contenido</span><span className="font-mono font-semibold">{item.contentCode}</span></div><div><span className="block text-[10px] text-muted sm:hidden">Lote</span><span className="font-mono">{item.lotCode}</span></div><div><span className="block text-[10px] text-muted sm:hidden">Entrada</span>{item.entryDate}</div><div><span className="block text-[10px] text-muted sm:hidden">Salida</span>{item.exitDate ?? <span className="font-semibold text-[#1f5c3a]">Actual</span>}</div><div><span className="block text-[10px] text-muted sm:hidden">Volumen</span>{formatLiters(item.volumeLiters)} L</div></div>)}<p className="text-[11px] text-muted">Las ocupaciones cerradas son historia y no se presentan como contenido actual.</p></div>}
      {tab === 'Limpieza y mantenimiento' && <div className="mt-4 space-y-2">{deposit.cleaningHistory.length === 0 ? <p className="rounded-xl bg-white p-5 text-[12px] text-muted">Sin actuaciones registradas en esta demostración.</p> : deposit.cleaningHistory.map((item) => <div key={`${item.date}-${item.action}`} className="rounded-xl border border-border bg-white p-3 text-[12px]"><div className="flex justify-between gap-2"><strong>{item.action}</strong><span className="text-muted">{item.date}</span></div><p className="m-0 mt-1 text-muted">{item.responsible} · {item.result}</p></div>)}{(deposit.status === 'maintenance' || deposit.status === 'cleaning') && <p className="rounded-xl bg-[#efeff5] p-3 text-[11.5px] text-[#43435c]">Este depósito no admite entradas hasta completar la revisión y liberación correspondiente.</p>}</div>}
    </section><aside className="space-y-4"><section className="rounded-[18px] border border-border bg-[#fdfbfc] p-4 sm:p-5"><div className="flex items-center justify-between gap-2"><h2 className="text-[16px] font-semibold">Contenido actual</h2>{occupation && <span className="rounded-full bg-plum-soft px-2 py-1 text-[10px] font-semibold text-plum">Ocupado</span>}</div>{occupation ? <><p className="mt-3 font-mono text-[14px] font-semibold">{occupation.contentCode}</p><p className="mt-1 text-[12px] text-muted">{occupation.category} · {occupation.lotCode}</p><p className="mt-3 font-mono text-[22px]">{formatLiters(occupiedLiters)} L</p><div className="mt-1 h-1.5 rounded-full bg-[#efe6ea]"><div className="h-full rounded-full bg-plum" style={{ width: `${Math.min(100, fill)}%` }} /></div><p className="mt-1 text-[11px] text-muted">{fill} % de capacidad útil · el llenado no indica avance fermentativo</p><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-1"><div className="rounded-xl bg-white p-3 text-[11.5px]"><div className="text-muted">Fermentación alcohólica</div><strong className="mt-1 block">{occupation.alcoholicState}</strong></div><div className="rounded-xl bg-white p-3 text-[11.5px]"><div className="text-muted">Maloláctica</div><strong className="mt-1 block">{occupation.malolacticState}</strong></div></div>{deposit.priority !== 'none' && <p className="mt-3 text-[11.5px] font-semibold text-[#8e1f33]">Prioridad: {statusLabel(deposit)}</p>}</> : <p className="mt-3 text-[12px] leading-5 text-muted">Sin contenido actual. No se muestran como vigentes los estados del producto anterior.</p>}</section>{occupation && <section className="rounded-[18px] border border-border bg-[#fdfbfc] p-4 sm:p-5"><h2 className="text-[16px] font-semibold">Últimas medidas</h2><dl className="mt-3 space-y-2 text-[11.5px]">{(deposit.code === 'DEP-014' ? [['Acidez volátil', '0,72 g/L · 14 sep'], ['pH', '3,42 · 14 sep'], ['Temperatura', '18,6 °C · hoy 07:05'], ['Azúcares reductores', 'No medido']] : [['Último control', deposit.lastControl ?? 'Sin controles'], ['Vigencia', deposit.lastControlAge ?? 'Pendiente']]).map(([label, value]) => <div key={label} className="flex justify-between gap-3 border-b border-border pb-2"><dt className="text-muted">{label}</dt><dd className="m-0 text-right font-semibold">{value}</dd></div>)}</dl></section>}</aside></div>
    {editing && <EditDeposit deposit={deposit} onClose={() => setEditing(false)} onSaved={(updated) => { setDeposit(updated); setEditing(false) }} />}
  </div>
}
